### PR TITLE
Added documentation for the triple anonymous peer review system

### LINKED ISSUE #4426: Write documentation for triple-anonymous review
**Describe the area of the documentation you would like updated/added.**
with the implementation of #4416, we need to update the documentation regarding
- Configuration
- What is considered PII

### PR DESCRIPTION
**Pull request by ajrbyers**
Closes #4426

### CODE REVIEW

**Review by S-Haime — APPROVED** [review]
Made some changes to language, otherwise no immediate issues. Will review and edit in more depth as part of Documentation project.

**Comment by S-Haime** [comment]
Cannae find the original PR, but we may also need a 'quiet' notification to Editors when a Section-Editor assigns the Author as Reviewers in triple anonymous. The Author is ofc also blocked from doing the review (I checked) and if 1-click review is not enabled, they cannot decline. If they do have 1-click access, they could potentially review their own paper. (Uncertain as I get a server error when I test). Nevertheless, the Editor ought to be notified to keep an eye on this and ensure the author declines to review without informing the section-editor of the reason why,

**Comment by S-Haime** [comment]
Actually we DEFINITELY need an alert and a half if Authors do ever review their own work (as it would be easy to overlook in a journal with a large number of articles in review - on the overview you'd only see initials, so you'd have to open the article review page to check whilst having the correct permissions).

**Comment by ajrbyers** [comment]
> Actually we DEFINITELY need an alert and a half if Authors do ever review their own work (as it would be easy to overlook in a journal with a large number of articles in review - on the overview you'd only see initials, so you'd have to open the article review page to check whilst having the correct permissions).

When triple anon is enabled perhaps we should just filter out the authors from the reviewer list?

**Review by mauromsl — APPROVED** [review]

**Comment by S-Haime** [comment]
> > Actually we DEFINITELY need an alert and a half if Authors do ever review their own work (as it would be easy to overlook in a journal with a large number of articles in review - on the overview you'd only see initials, so you'd have to open the article review page to check whilst having the correct permissions).
> 
> When triple anon is enabled perhaps we should just filter out the authors from the reviewer list?

I considered that, but it would give the game away to the section editor.

**Pull request merged**
